// <auto-generated />
namespace ASP.NET_Developer_Challenge_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202012070818245_initialCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
